site_name: oVirt Infra Docs
site_description: oVirt infrastructure documentation
site_author: oVirt infra team
site_dir: exported-artifacts
use_directory_urls: false
theme: readthedocs
repo_url: https://gerrit.ovirt.org/#/admin/projects/infra-docs
repo_name: Gerrit
pages:
  - Home: index.markdown
  - General:
    - 'Communication': 'General/Communication.markdown'
    - 'Infra Bash style guide': 'General/Infra_Bash_style_guide.markdown'
    - 'How to add a mirror': 'General/Mirror.markdown'
    - 'Service Upgrade Checklist': 'General/Service_Upgrade_Checklist.markdown'
    - 'Puppet dev tips': 'General/Puppet.markdown'
    - 'Creating Gerrit projects': 'General/Creating_Gerrit_Projects.markdown'
    - 'Merging Gerrit accounts': 'General/Gerrit_account_merge.markdown'
    - 'Encrypting/decrypting with you own PGP key': 'General/PGP_howto.markdown'
  - 'Phoenix lab':
    - 'Overview': 'Phoenix_Lab/Overview.markdown'
    - 'oVirt hosts': 'Phoenix_Lab/oVirt_Hosts.markdown'
    - 'Configureing the ssh tunnel to get spice': 'Phoenix_Lab/Ssh_Spice_Tunnel.markdown'
    - 'Storage hosts': 'Phoenix_Lab/Storage_Hosts.markdown'
    - 'Jenkins VM': 'Phoenix_Lab/Jenkins.markdown'
  - CI:
    - 'Build and test standards': 'CI/Build_and_test_standards.markdown'
    - 'The transactional mirrors': 'CI/Transactional_mirrors.markdown'
    - 'List of CI mirrors': 'CI/List_of_mirrors.markdown'
    - 'Proxy': 'CI/Proxy.markdown'
    - 'System Groovy Jenkins Scripts': 'CI/System_groovy_jenkins_scripts.markdown'
    - 'Gerrit custom hooks': 'CI/Gerrit_Hooks.markdown'
    - 'Adding a yamlized jobs to Jenkins with JJB': 'CI/Adding_yamlized_jobs_with_JJB.markdown'
